/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SerwisAutaLecznaRouteImport } from './routes/serwis-auta-leczna'
import { Route as MechanikLecznaRouteImport } from './routes/mechanik-leczna'
import { Route as KlimatyzacjaLecznaRouteImport } from './routes/klimatyzacja-leczna'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SerwisAutaLecznaRoute = SerwisAutaLecznaRouteImport.update({
  id: '/serwis-auta-leczna',
  path: '/serwis-auta-leczna',
  getParentRoute: () => rootRouteImport,
} as any)
const MechanikLecznaRoute = MechanikLecznaRouteImport.update({
  id: '/mechanik-leczna',
  path: '/mechanik-leczna',
  getParentRoute: () => rootRouteImport,
} as any)
const KlimatyzacjaLecznaRoute = KlimatyzacjaLecznaRouteImport.update({
  id: '/klimatyzacja-leczna',
  path: '/klimatyzacja-leczna',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/klimatyzacja-leczna': typeof KlimatyzacjaLecznaRoute
  '/mechanik-leczna': typeof MechanikLecznaRoute
  '/serwis-auta-leczna': typeof SerwisAutaLecznaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/klimatyzacja-leczna': typeof KlimatyzacjaLecznaRoute
  '/mechanik-leczna': typeof MechanikLecznaRoute
  '/serwis-auta-leczna': typeof SerwisAutaLecznaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/klimatyzacja-leczna': typeof KlimatyzacjaLecznaRoute
  '/mechanik-leczna': typeof MechanikLecznaRoute
  '/serwis-auta-leczna': typeof SerwisAutaLecznaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/klimatyzacja-leczna'
    | '/mechanik-leczna'
    | '/serwis-auta-leczna'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/klimatyzacja-leczna'
    | '/mechanik-leczna'
    | '/serwis-auta-leczna'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/klimatyzacja-leczna'
    | '/mechanik-leczna'
    | '/serwis-auta-leczna'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KlimatyzacjaLecznaRoute: typeof KlimatyzacjaLecznaRoute
  MechanikLecznaRoute: typeof MechanikLecznaRoute
  SerwisAutaLecznaRoute: typeof SerwisAutaLecznaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serwis-auta-leczna': {
      id: '/serwis-auta-leczna'
      path: '/serwis-auta-leczna'
      fullPath: '/serwis-auta-leczna'
      preLoaderRoute: typeof SerwisAutaLecznaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechanik-leczna': {
      id: '/mechanik-leczna'
      path: '/mechanik-leczna'
      fullPath: '/mechanik-leczna'
      preLoaderRoute: typeof MechanikLecznaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klimatyzacja-leczna': {
      id: '/klimatyzacja-leczna'
      path: '/klimatyzacja-leczna'
      fullPath: '/klimatyzacja-leczna'
      preLoaderRoute: typeof KlimatyzacjaLecznaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KlimatyzacjaLecznaRoute: KlimatyzacjaLecznaRoute,
  MechanikLecznaRoute: MechanikLecznaRoute,
  SerwisAutaLecznaRoute: SerwisAutaLecznaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
